server:
  port: ":8080"  # Default port
  allowed_origins:
    - "https://krisadabig.github.io"

database:
  username: "postgres"
  password: "postgres"
  host: "localhost"
  port: 5432
  dbname: "postgres"