services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supreme-ms-item
    restart: unless-stopped
    ports:
      - "8080:1323"
    env_file:
      - .env
    environment:
      - CONFIG_FILE=/config.yaml
    volumes:
      - ./config.yaml:/config.yaml
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Optional: Uncomment and configure if you want to run Supabase locally
  # supabase:
  #   image: supabase/postgres
  #   environment:
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_DB: ${DB_NAME}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - supabase_data:/var/lib/postgresql/data

# volumes:
#   supabase_data:
